development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: chat_system_development
  pool: 5
  username: root
  password: password
  host: db
  port: 3306

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: chat_system_test
  pool: 5
  username: root
  password: password
  host: db
  port: 3306

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: chat_system_production
  pool: 5
  username: root
  password: password
  host: db
  port: 3306
